# services/ai-scope-service/estimator.py
# Core AI estimation logic — calls OpenAI with or without vision

import json
import logging
from typing import Optional

from openai import AsyncOpenAI

from config import settings
from models import ScopeEstimate

logger = logging.getLogger(__name__)

# Initialise client lazily so the service starts even without a key configured
_client: Optional[AsyncOpenAI] = None


def get_client() -> AsyncOpenAI:
    global _client
    if _client is None:
        _client = AsyncOpenAI(api_key=settings.openai_api_key)
    return _client


SYSTEM_PROMPT = """You are an expert field estimator for a cooperative home-services platform.
Your job is to analyse a household repair or service request and return a structured JSON estimate.

Rules:
- Be conservative but fair — don't under-quote (hurts workers) or over-quote (hurts customers).
- Base your estimate on Delhi/NCR market rates for skilled cooperative workers.
- If an image is provided, use visual cues to assess damage severity.
- Return ONLY valid JSON. No prose, no markdown fences.

JSON schema to return:
{
  "standard_hours": <number, e.g. 1.5>,
  "difficulty_tier": <"Standard" | "Complex" | "Emergency">,
  "parts_estimate_inr": <number, e.g. 250>,
  "recommended_base_price": <number — labour + parts>,
  "confidence_score": <0.0–1.0>,
  "notes": <one sentence explanation>,
  "detected_category": <"Plumbing"|"Electrical"|"Carpentry"|"Caregiving"|"Cleaning"|"Appliance Repair"|"Painting"|"Other">
}

Difficulty tiers:
- Standard: routine maintenance, simple fixes
- Complex: multiple components, specialised tools, 2+ hours
- Emergency: safety risk, urgent, outside business hours markup
"""


def _build_user_content(
    description: str,
    category: Optional[str],
    image_base64: Optional[str],
) -> list:
    """Build the messages content list, adding image block if provided."""
    text_block = {
        "type": "text",
        "text": (
            f"Service category hint: {category}\n\n"
            if category
            else ""
        ) + f"Customer description:\n{description}",
    }

    if image_base64:
        return [
            text_block,
            {
                "type": "image_url",
                "image_url": {
                    "url": f"data:image/jpeg;base64,{image_base64}",
                    "detail": "low",  # use low detail to save tokens
                },
            },
        ]
    return [text_block]


def _fallback_estimate(category: Optional[str]) -> ScopeEstimate:
    """
    Rule-based fallback when OpenAI is unavailable or returns bad JSON.
    Returns a sensible default so the booking flow never breaks.
    """
    cat = category or "Other"
    base = settings.base_rates.get(cat, 500)
    return ScopeEstimate(
        standard_hours=1.5,
        difficulty_tier="Standard",
        parts_estimate_inr=200.0,
        recommended_base_price=float(base * 1.5 + 200),
        confidence_score=0.4,
        notes="Estimate generated by rule-based fallback. AI model unavailable.",
        detected_category=cat,
    )


async def estimate_scope(
    description: str,
    image_base64: Optional[str] = None,
    service_category: Optional[str] = None,
) -> ScopeEstimate:
    """
    Call the OpenAI API (with vision if image provided) and parse the estimate.
    Falls back to rule-based estimate on any error.
    """
    if not settings.openai_api_key:
        logger.warning("OPENAI_API_KEY not set — using rule-based fallback")
        return _fallback_estimate(service_category)

    model = settings.model if image_base64 else settings.text_model
    content = _build_user_content(description, service_category, image_base64)

    try:
        client = get_client()
        response = await client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": content},
            ],
            response_format={"type": "json_object"},
            temperature=0.2,
            max_tokens=400,
        )

        raw = response.choices[0].message.content or "{}"
        data = json.loads(raw)

        # Apply difficulty multiplier to validate price floor
        cat = data.get("detected_category") or service_category or "Other"
        tier = data.get("difficulty_tier", "Standard")
        base_rate = settings.base_rates.get(cat, 500)
        multiplier = settings.difficulty_multipliers.get(tier, 1.0)
        hours = float(data.get("standard_hours", 1.5))
        parts = float(data.get("parts_estimate_inr", 0))
        min_price = base_rate * multiplier * hours + parts

        # Ensure recommended price is at least the floor
        recommended = max(float(data.get("recommended_base_price", min_price)), min_price)

        return ScopeEstimate(
            standard_hours=hours,
            difficulty_tier=tier,
            parts_estimate_inr=parts,
            recommended_base_price=round(recommended, 2),
            confidence_score=float(data.get("confidence_score", 0.7)),
            notes=data.get("notes"),
            detected_category=cat,
        )

    except json.JSONDecodeError as exc:
        logger.error("Failed to parse AI JSON: %s", exc)
        return _fallback_estimate(service_category)
    except Exception as exc:
        logger.error("OpenAI call failed: %s", exc)
        return _fallback_estimate(service_category)
